### PR TITLE
Ensure that PR builds don't sign and don't promote.

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse/gef/issues/108

### CODE REVIEW

**Comment by merks** [comment]
I manually replayed the verification build with a copy of the changed Jenkinsfile.  The build description support is helpful to see the values of the parameters used for the build:

image

The master branch has build successfully though not yet with promotion:

image

@miklossy

I hope this is the last change I need to make for the time being.  Thank you for your support!

**Comment by merks** [comment]
Woo hoo.   PR builds work!

**Comment by merks** [comment]
I have the first promoted build working now too:

https://download.eclipse.org/tools/gef/fx/

**Comment by miklossy** [comment]
Nice job, @merks !

**Pull request merged**
