### PR TITLE
Simply the target platform configuration

### PR DESCRIPTION
**Pull request by merks**
Eliminate the duplication of profiles to support different target platforms and instead use a system property to choose the target. Generate a 2024-03 target platform.
Provide an m2e launcher for running the Tycho build in the IDE.

### CODE REVIEW

**Comment by merks** [comment]
@miklossy 

I can't test the pipeline changes until this is merged.   You may wish to consider that it's much more direct to help maintain this stuff with commit rights than with the current approach...

**Comment by miklossy** [comment]
Thanks for your PR @merks !

I would be happy to nominate you as an Eclipse GEF committer, as announced in this [comment](https://github.com/eclipse/gef/issues/108#issuecomment-1824777724), but therefore I need you email address! :-)

**Comment by miklossy** [comment]
I am merging this PR now, @merks , but I am still waiting for your email address to be able to nominate you as an Eclipse GEF committer. Thanks!

**Comment by merks** [comment]
Thank you.  😄 

Here's a trick I found Googling.  Append `.patch` to the commit URL of a commit authored by a particular user, and presto:

image

**Comment by merks** [comment]
FYI, I can see that the Jenkinsfile change works because it shows the selected target platform in the build description:

image

**Comment by miklossy** [comment]
I have just started your nomination, @merks !

https://projects.eclipse.org/projects/tools.gef/elections/election-ed-merks-committer-eclipse-graphical-editing-framework-gef

**Comment by merks** [comment]
Yes, I see it in the Tools PMC mailing list.  Thank you!  😀 

When it's done I can more easily and update the README stuff and host the setup in the repository itself where it belongs.

I have a setup for GEF classic as well, that I hope to find time to get into a final state for contribution.

**Comment by azoitl** [comment]
> I have a setup for GEF classic as well, that I hope to find time to get into a final state for contribution.

That is amazing. Thanks a lot @merks.

**Pull request merged**
